/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion;

/**
 *
 * @author piero
 */
public class Aplicacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aplicacion.class.getName());

    /**
     * Creates new form Aplicacion
     */
    SistemaFacturacion sistema;
    
    public Aplicacion() {
        initComponents();
        sistema = new SistemaFacturacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbDocumentoCliente = new javax.swing.JLabel();
        jlbNombreCliente = new javax.swing.JLabel();
        jlbTelefonoCliente = new javax.swing.JLabel();
        jlbDireccionCliente = new javax.swing.JLabel();
        jlbCodigoProducto = new javax.swing.JLabel();
        jlbNombreProducto = new javax.swing.JLabel();
        jlbPrecioUnitario = new javax.swing.JLabel();
        jlbCantidad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtDocumentoCliente = new javax.swing.JTextField();
        jtxtNombreCliente = new javax.swing.JTextField();
        jtxtTelefonoCliente = new javax.swing.JTextField();
        jtxtDireccionCliente = new javax.swing.JTextField();
        jtxtCodigoProducto = new javax.swing.JTextField();
        JtxtNombreProducto = new javax.swing.JTextField();
        jtxtPrecioUnitario = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jbtnBuscarCliente = new javax.swing.JButton();
        jbtnBuscarProducto = new javax.swing.JButton();
        jbtnGenerarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaFactura = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtMensajeError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1122, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registrar Producto", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1122, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registrar Cliente", jPanel2);

        jlbDocumentoCliente.setText("RUC o DNI");

        jlbNombreCliente.setText("Nombre");

        jlbTelefonoCliente.setText("Telefono");

        jlbDireccionCliente.setText("Direccion");
        jlbDireccionCliente.setToolTipText("");

        jlbCodigoProducto.setText("Codigo de producto");
        jlbCodigoProducto.setToolTipText("");

        jlbNombreProducto.setText("Nombre del producto");
        jlbNombreProducto.setToolTipText("");

        jlbPrecioUnitario.setText("Precio Unitario");
        jlbPrecioUnitario.setToolTipText("");

        jlbCantidad.setText("Cantidad");
        jlbCantidad.setToolTipText("");

        jLabel9.setText("Cantidad");
        jLabel9.setToolTipText("");

        jTextField9.setText("jTextField1");

        jbtnBuscarCliente.setText("Buscar cliente");
        jbtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarClienteActionPerformed(evt);
            }
        });

        jbtnBuscarProducto.setText("Buscar Producto");
        jbtnBuscarProducto.setToolTipText("");
        jbtnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarProductoActionPerformed(evt);
            }
        });

        jbtnGenerarFactura.setText("Generar Factura");
        jbtnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerarFacturaActionPerformed(evt);
            }
        });

        jtxaFactura.setColumns(20);
        jtxaFactura.setRows(5);
        jScrollPane1.setViewportView(jtxaFactura);

        jtxtMensajeError.setColumns(20);
        jtxtMensajeError.setRows(5);
        jScrollPane2.setViewportView(jtxtMensajeError);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbDocumentoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbTelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbPrecioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(JtxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtxtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jbtnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDocumentoCliente)
                            .addComponent(jtxtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBuscarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombreCliente)
                            .addComponent(jtxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTelefonoCliente)
                            .addComponent(jtxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDireccionCliente)
                            .addComponent(jtxtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCodigoProducto)
                            .addComponent(jtxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBuscarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombreProducto)
                            .addComponent(JtxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPrecioUnitario)
                            .addComponent(jtxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCantidad)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jbtnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );

        jlbPrecioUnitario.getAccessibleContext().setAccessibleName("Precio unitario");
        jLabel9.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Facturacion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarClienteActionPerformed
        boolean clienteEncontrado = false;
        int posicion = sistema.buscarCliente(jtxtDocumentoCliente.getText());
       
            if (posicion != -1) {
                Cliente cliente = sistema.clientes[posicion];
                jtxtNombreCliente.setText(cliente.getNombre());
                jtxtTelefonoCliente.setText(cliente.getTelefono());
                jtxtDireccionCliente.setText(cliente.getDireccion());
                clienteEncontrado = true;
               
            }
        
        if (clienteEncontrado == false) {
            jtxtMensajeError.append("Error, cliente no encontrado, por favor registre al cliente primero");
        }
    }//GEN-LAST:event_jbtnBuscarClienteActionPerformed

    private void jbtnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarProductoActionPerformed
        boolean productoEncontrado = false;
        int posicion = sistema.buscarProducto(jtxtCodigoProducto.getText());
        if (posicion != -1) {
            Producto producto = sistema.productos[psocion];
            JtxtNombreProducto.setText(producto.getNombre());
            jtxtPrecioUnitario.setText(String.valueOf(producto.getPrecioUnitario()));
            productoEncontrado = true;
            
        }
        if (productoEncontrado== false) {
            jtxtMensajeError.append("Error, producto no encontrado");
            
        }
    }//GEN-LAST:event_jbtnBuscarProductoActionPerformed

    private void jbtnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerarFacturaActionPerformed
        Factura factura = new Factura();
        
        factura.setNumeroFactura = "F" + String.format("%04d",sistema.cantidadFacturas + 1);
        factura.setClienteDocumento = jtxtDocumentoCliente.getText();
        factura.setClienteNombre = jtxtNombreCliente.getText();
        
        factura.calcularSubtotal();
        factura.calcularIGV();
        factura.calcularTotal();
        sistema.generarFactura(factura);
        
        String resumenFactura = "";
        resumenFactura += "Factura N°: "+ factura.getNumeroFactura + "\n";
        resumenFactura += "Cliente: " + factura.getClienteNombre+"\n";
        resumenFactura += "Documento" + factura.getClienteDocumento + "\n\n";
        resumenFactura += "Detalles de la compra: \n";
        for (int i = 0; i < factura.getCantidadItems; i++) {
            resumenFactura += "- "+factura.getCodigosProducto[i] + " |Cant: "+factura.getCantidades[i]
                    + " | Precio: $ "+ factura.getPrecioUnitario[i] + "\n";
            
        }
        resumenFactura += "\nSubtotal: $ " + String.format("%.2f", factura.getSubtotal +"\n");
        resumenFactura += "IGV(18%): $ "+String.format("%.2f", factura.getIGV)+"\n";
        resumenFactura += "Total: $ "+String.format("%.2f", factura.getTotal)+"\n";
        
        jtxaFactura.setText(resumenFactura);
        
    }//GEN-LAST:event_jbtnGenerarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aplicacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtNombreProducto;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbtnBuscarCliente;
    private javax.swing.JButton jbtnBuscarProducto;
    private javax.swing.JButton jbtnGenerarFactura;
    private javax.swing.JLabel jlbCantidad;
    private javax.swing.JLabel jlbCodigoProducto;
    private javax.swing.JLabel jlbDireccionCliente;
    private javax.swing.JLabel jlbDocumentoCliente;
    private javax.swing.JLabel jlbNombreCliente;
    private javax.swing.JLabel jlbNombreProducto;
    private javax.swing.JLabel jlbPrecioUnitario;
    private javax.swing.JLabel jlbTelefonoCliente;
    private javax.swing.JTextArea jtxaFactura;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtCodigoProducto;
    private javax.swing.JTextField jtxtDireccionCliente;
    private javax.swing.JTextField jtxtDocumentoCliente;
    private javax.swing.JTextArea jtxtMensajeError;
    private javax.swing.JTextField jtxtNombreCliente;
    private javax.swing.JTextField jtxtPrecioUnitario;
    private javax.swing.JTextField jtxtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
